const CARS = {
    LOAD : 'REQUEST_CAR_DATA',
    LOAD_SUCCESS : 'RECEIVED_CAR_DATA',
    LOAD_FILTER : 'REQUEST_FILTERED_CAR_DATA',
    DO_FILTER : 'FILTER_CAR_DATA',
    LOAD_FILTER_SUCCESS : 'RECEIVED_FILTERED_CAR_DATA'
}

export default CARS